trigger:
  - feature/azure-pipeline

stages:
  - stage: test
    jobs:
      - job: tsaving
        displayName: "Deploy tsaving"
        pool: 
          vmImage: "ubuntu-18.04"
        steps:
          - task: Docker@2
            displayName: Login
            inputs:
              command: login
              containerRegistry: baitregistry
          - task: Docker@2
            displayName: "Build and Push"
            inputs:
              command: buildAndPush
              containerRegistry: baitregistry
              repository: baitregistry.azurecr.io/tsaving
              tag: $(BuildNumber)
          - task: HelmInstaller@1
            displayName: Helm installer
            inputs: 
              helmVersionToInstall: 3.3.0
          - task: HelmDeploy@0
            displayName: Helm upgrade
            inputs:
              kubernetesServiceEndpoint: baitkubernetescluster
              connectionType: 'Kubernetes Service Connection'
              azureResourceGroup: ba-it-tools
              kubernetesCluster: baitkubernetescluster
              command: upgrade
              chartType: filepath
              chartPath: tsavingchart
              releaseName: tsaving
              install: true
              waitForExecution: false
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure-pipeline')
