trigger:
  - feature/azure-pipeline

stages:
  - stage: test
    jobs:
      - job: 'Deploy Tsaving'
        displayName: "Build and Push Docker"
        pool: 
          vmImage: "ubuntu-18.04"
        steps:
          - task: Docker@2
            displayName: "build and push"
            inputs:
              command: buildAndPush
              containerRegistry: 'Container Registry'
              dockerRegistryEndpoint: baitregistry
              repository: baitregistry.azurecr.io/tsaving:$(BuildNumber)
          - task: HelmInstaller@1
            displayName: Helm installer
            inputs: 
              helmVersionToInstall: 3.3.0
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure-pipeline')
