filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
 
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
 
filebeat.modules:
- module: elasticsearch
 
processors:
- add_cloud_metadata: ~
 
output.elasticsearch:
  hosts: 'elasticsearch:9200'
  # username: 'elastic'
  # password: 'changeme'